name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Bazelisk
        run: npm install @bazel/bazelisk

      - name: Run tests
        run: npx bazelisk test ...
